// Fiddle class. Ignore stylecop here.
// <auto-generated>
#pragma warning disable CS0168 

using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Diagnostics;
using System.Linq;
using System.ServiceProcess;

namespace Tests
{
    [TestClass]
    public class Fiddle
    {
        [TestMethod]
        [Ignore]
        public void FiddleMethod1()
        {
            var processes = Process.GetProcesses();

            foreach (var p in processes)
            {
                try
                {
                    var m = p.MainModule;
                    var startTime = p.StartTime;
                }
                catch (System.Exception ex)
                {
                    System.Diagnostics.Trace.WriteLine($"\"{p.ProcessName}\",");
                }
            }
        }
    }
}