// Fiddle class. Ignore stylecop here.
// <auto-generated>
#pragma warning disable CS0168 

using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Diagnostics;

namespace Tests
{
    [TestClass]
    public class Fiddle
    {
        [TestMethod]
        public void FiddleMethod1()
        {
            var processes = Process.GetProcessesByName("linqpad");

            foreach (var p in processes)
            {
                try
                {
                    var m = p.MainModule;
                }
                catch (System.Exception ex)
                {
                    System.Diagnostics.Trace.WriteLine($"\"{p.ProcessName}\",");
                }
            }
        }
    }
}
#pragma warning restore CS0168